language: java
jdk:
  - openjdk11

branches:
  only:
    - develop

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - 6230nana@gmail.com
